[10] Add homework 10
funny-code-404/react-course pull request #256
Opened 2022-02-25 04:06 UTC by svetlana-botyan

2022-02-25 22:33 UTC, funny-code-404 requested changes

2022-02-25 22:33 UTC, funny-code-404 commented on 10/svetlana-botyan/src/components/CommentPage/index.jsx
> +  state = useSelector(commentDataSelector);
1) для чего здесь переменная?
2) зачем данные хранить в stat роута, если есть redux?

2022-02-25 22:33 UTC, funny-code-404 commented on 10/svetlana-botyan/src/components/CommentsPage/index.jsx
> +          key={uuidv4()}
не используй ключом uuid - он будет каждый раз создаваться новый. лучше использовать id каждого элемента

2022-02-28 22:08 UTC, svetlana-botyan commented on 10/svetlana-botyan/src/components/CommentsPage/index.jsx
> +          key={uuidv4()}
убрала

2022-02-28 22:09 UTC, svetlana-botyan commented on 10/svetlana-botyan/src/components/CommentPage/index.jsx
> +  state = useSelector(commentDataSelector);
обновила

2022-06-03 18:39 UTC, closed without merging